logging:
  #   Сохранить логи в файл
  #    file:
  #        name: createIndicatorData.log
  #        path: /
  level:
    com.finance.strategyGeneration: INFO
    root: INFO
    org.springframework.jdbc.core: INFO

server:
  port: 8082

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    allow-circular-references: true
  mvc:
    format:
      # Устанавливает формат для конвертации дат в формат iso
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5434/strategies-db
    username: algotrading
    password: parol
    driver-class-name: org.postgresql.Driver
    jpa:
      # Транзакции не будет созданы на уровне контроллеров если стоит аннотация @Transactional
      open-in-view: false

app:
  populationCreation:
    numberOfRandomIndividual: 5
    numberOfTheBestIndividual: 5
    isNeedToCreateDescriptionToCloseADeal: false
  kafka:
    producer:
      client_id_config: StrategyGenerationProducer
      bootstrap_servers_config: localhost:9092
      acks_config: 1
      retries_config: 2
      # Какая должна быть группа запросов перед отправкой
      batch_size_config: 2500
      # Ожидание заполнения группы запросов в batch_size_config
      linger_ms_config:  100
      buffer_memory_config: 33_554_432
      max_block_ms_config: 1_000
      topic_name: untestedStrategies
    consumer:
      bootstrap_servers_config: localhost:9092
      group_id_config: StrategyGenerationConsumer
      group_instance_id_config: untestedStrategiesGroup
      enable_auto_commit_config: true
      auto_commit_interval_ms_config: 100
      auto_offset_reset_config: earliest
      # Количество данных получаемых за раз
      max_poll_records_config: 1000
      # Дает понгимание для Kafka что consumer живой
      max_poll_interval_ms_config: 50000
      topic_name: untestedStrategies
      timeout_duration: 2000
