logging:
  #   Сохранить логи в файл
  #    file:
  #        name: createIndicatorData.log
  #        path: /
  level:
    root: INFO
    org.springframework.jdbc.core: INFO

server:
  port: 8082

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    allow-circular-references: true
  mvc:
    format:
      # Устанавливает формат для конвертации дат в формат iso
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5434/strategies-db
    username: algotrading
    password: parol
    driver-class-name: org.postgresql.Driver
    jpa:
      # Транзакции не будет созданы на уровне контроллеров если стоит аннотация @Transactional
      open-in-view: false

app:
  populationCreation:
    frontierForCreatingNewStrategies: 1000
    numberOfRandomIndividual: 10
    numberOfTheBestIndividual: 10
    isNeedToCreateDescriptionToCloseADeal: false
  kafka:
    client_id_config: StrategyGenerationProducer
    bootstrap_servers_config: localhost:9092
    acks_config: 1
    retries_config: 1
    batch_size_config: 16384
    linger_ms_config:  10
    buffer_memory_config: 33_554_432
    max_block_ms_config: 1_000
    topic_name: untestedStrategies
