FROM postgres:14.4

ENV POSTGRES_USER algotrading
ENV POSTGRES_PASSWORD parol
ENV POSTGRES_DB indicator-data-db


# Собрать image
# docker build -t indicator-data-db:indicator-data-db .

# Запустить контейнер
# docker run -d -p 5433:5432 -t --name indicator-data-db indicator-data-db:indicator-data-db

# Посмотреть логи
# docker logs -f indicator-data-db