FROM postgres:14.4

ENV POSTGRES_USER algotrading
ENV POSTGRES_PASSWORD parol
ENV POSTGRES_DB strategies-db


# Собрать image
# docker build -t strategies-db:strategies-db .

# Запустить контейнер
# docker run -d -p 5433:5432 -t --name strategies-db strategies-db:strategies-db

# Посмотреть логи
# docker logs -f strategies-db