package com.finance.strategyGeneration.stagesOfGeneticAlgorithm.createPopulation.randomPopulation.strategiesForCreatingRandomPopulations.generatorRandomIndicators;

import com.finance.strategyDescriptionParameters.CurrencyPair;
import com.finance.strategyGeneration.model.InformationOfIndicator;

public interface GeneratorOfRandomIndicators {
    InformationOfIndicator getRandomIndicator(CurrencyPair currencyPair);
}
