


app:
  geneticAlgorithm:
    url: http://localhost:8082/
  kafka:
    bootstrap_servers_config: localhost:9092
    group_id_config: checkStrategyConsumer
    group_instance_id_config: untestedStrategiesGroup
    enable_auto_commit_config: true
    auto_commit_interval_ms_config: 100
    auto_offset_reset_config: earliest
    max_poll_records_config: 3
    max_poll_interval_ms_config: 300
    topic_name: untestedStrategies
  checkStrategy:
      theBorderForGettingNewDescriptionOfStrategy: 10
      threadPoolSize: 16