FROM postgres:14.4

ENV POSTGRES_USER algotrading
ENV POSTGRES_PASSWORD parol
ENV POSTGRES_DB candles-db


# Собрать image
# docker build -t candles-db:candles-db .

# Запустить контейнер
# docker run --name candles-db -d -p 5433:5432 -t candles-db:candles-db

# Посмотреть логи
# docker logs -f candles-db

# Содать volume
#docker volume create candlesVolume